package com.example.tugaslistwisata

import android.content.Intent
import android.os.Bundle
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val wisataList = listOf(
            Wisata("Lawang Sewu", "Lawang Sewu adalah gedung bersejarah yang terletak di Semarang, Jawa Tengah, Indonesia, dan dikenal sebagai \"seribu pintu\" karena arsitekturnya yang megah serta banyaknya pintu yang ada. Dibangun pada tahun 1904 oleh arsitek Belanda C.P. Wolff Schoemaker, gedung ini awalnya digunakan sebagai kantor Perusahaan Kereta Api Hindia Belanda. Selain keindahan arsitekturnya, Lawang Sewu juga terkenal dengan kisah-kisah mistis yang menyelimuti tempat ini, menjadikannya sebagai salah satu lokasi angker di Indonesia. Gedung ini memiliki lorong-lorong panjang, jendela-jendela besar, serta menara tinggi yang memberikan kesan megah, dan saat ini menjadi objek wisata yang menarik ribuan pengunjung setiap tahun. Para wisatawan dapat mengeksplorasi sejarah gedung ini, termasuk peristiwa penting seperti penggunaannya sebagai markas tentara Jepang selama Perang Dunia II, menjadikan Lawang Sewu sebagai destinasi yang wajib dikunjungi untuk merasakan pesona sejarah dan arsitektur kolonial Indonesia.", R.drawable.lawang_sewu),
            Wisata("Sam Poo Kong", "Sam Poo Kong adalah sebuah tempat ibadah dan wisata yang terletak di Semarang, Jawa Tengah, Indonesia. Dikenal sebagai klenteng tertua di kota ini, Sam Poo Kong didedikasikan untuk Laksamana Cheng Ho, seorang pelaut Tiongkok yang terkenal dan berpengaruh pada abad ke-15. Kompleks klenteng ini memiliki arsitektur yang menakjubkan, menggabungkan elemen budaya Tionghoa dan lokal, dengan warna merah mencolok dan ornamen yang indah. Selain sebagai tempat beribadah, Sam Poo Kong juga merupakan destinasi wisata yang menarik, menawarkan pengalaman budaya yang kaya, pemandangan alam yang indah, serta berbagai festival yang meriah. Pengunjung dapat mengeksplorasi berbagai bangunan bersejarah, menikmati keindahan taman di sekitarnya, serta belajar tentang sejarah dan tradisi yang berkaitan dengan Laksamana Cheng Ho. Sam Poo Kong menjadi salah satu ikon budaya dan spiritual di Semarang, menarik perhatian wisatawan lokal dan mancanegara yang ingin merasakan keunikan warisan budaya Indonesia.", R.drawable.sam_poo_kong),
            Wisata("Kota Lama", "Kota Lama Semarang adalah kawasan bersejarah yang terletak di jantung kota Semarang, Jawa Tengah, Indonesia, dan dikenal sebagai \"Little Netherlands\" karena arsitektur kolonial Belandanya yang terawat dengan baik. Didirikan pada abad ke-19, kawasan ini memiliki berbagai bangunan bersejarah yang menampilkan gaya arsitektur Eropa, seperti Gereja Blenduk, yang merupakan gereja tertua di kota ini, serta sejumlah gudang dan kantor perusahaan dagang yang kini berfungsi sebagai kafe, galeri, dan pusat seni. Jalanan berlapis batu bata dan atmosfer nostalgia membuat Kota Lama menjadi tempat yang ideal untuk berjalan-jalan dan menjelajahi sejarah serta budaya Semarang. Selain itu, berbagai acara dan festival seni sering diadakan di kawasan ini, menjadikannya sebagai destinasi wisata yang menarik bagi pengunjung yang ingin merasakan pesona masa lalu serta kekayaan warisan budaya Indonesia. Kota Lama Semarang bukan hanya sekadar tempat wisata, tetapi juga merupakan cerminan sejarah dan perkembangan kota yang unik.", R.drawable.kota_lama),
            Wisata("Pagoda Avalokitesvara", "Pagoda Avalokitesvara adalah salah satu tempat ibadah yang megah dan bersejarah yang terletak di Semarang, Jawa Tengah, Indonesia, yang dikenal sebagai pusat kegiatan spiritual bagi umat Buddha. Pagoda ini memiliki arsitektur yang menawan dengan tujuh tingkat, dihiasi oleh ornamen-ornamen cantik dan patung Avalokitesvara, dewa welas asih dalam tradisi Buddha. Dibangun pada tahun 2006, pagoda ini tidak hanya berfungsi sebagai tempat ibadah, tetapi juga sebagai simbol toleransi beragama dan keindahan budaya yang mencerminkan kekayaan spiritual masyarakat Indonesia. Di sekitar pagoda terdapat taman yang rimbun, serta berbagai patung dan relief yang menggambarkan ajaran Buddha, menjadikannya sebagai tempat yang tenang untuk beribadah dan refleksi. Pagoda Avalokitesvara menjadi destinasi wisata yang menarik bagi pengunjung yang ingin mengeksplorasi kedamaian spiritual serta menikmati keindahan arsitektur dan lingkungan sekitarnya.", R.drawable.pagoda),
            Wisata("Masjid Agung Jawa Tengah", "Masjid Agung Jawa Tengah adalah salah satu masjid terbesar dan terindah di Indonesia, terletak di Semarang, Jawa Tengah. Dikenal dengan arsitekturnya yang megah, masjid ini menggabungkan berbagai elemen desain, termasuk gaya tradisional Jawa, Islam, dan kolonial, dengan kubah besar yang mencolok serta menara setinggi 99 meter yang menjadi ikon kota. Diresmikan pada tahun 2006, masjid ini tidak hanya berfungsi sebagai tempat ibadah, tetapi juga sebagai pusat kegiatan sosial dan budaya, serta wisata religi. Kompleks masjid dikelilingi oleh taman yang luas dan kolam, menciptakan suasana tenang yang ideal untuk berdoa dan merenung. Masjid Agung Jawa Tengah menjadi salah satu destinasi wisata religi yang populer, menarik pengunjung dari berbagai kalangan untuk menikmati keindahan arsitektur dan kedamaian yang ditawarkannya.", R.drawable.majt),
            Wisata("Museum Ranggawarsita", "Museum Ranggawarsita adalah museum budaya yang terletak di Semarang, Jawa Tengah, yang menyimpan dan memamerkan koleksi sejarah serta kebudayaan Jawa. Didirikan pada tahun 1975, museum ini menampilkan berbagai artefak berharga, seperti alat musik tradisional, senjata, perhiasan, dan kerajinan tangan, yang mencerminkan kekayaan budaya lokal. Selain itu, museum ini juga memiliki koleksi arkeologi, etnografi, dan sejarah, yang memberikan wawasan mendalam tentang perjalanan sejarah masyarakat Jawa. Dengan desain arsitektur yang klasik dan suasana yang tenang, Museum Ranggawarsita menjadi tempat yang ideal bagi pengunjung yang ingin belajar lebih banyak tentang warisan budaya dan sejarah Indonesia, serta menikmati keindahan koleksi yang dipamerkan.", R.drawable.museum),
            Wisata("Kampung Pelangi Semarang", "Kampung Pelangi adalah sebuah desa wisata yang terletak di Semarang, Jawa Tengah, yang dikenal dengan keindahan warna-warni cat dinding rumahnya yang mencolok dan atraktif. Dikembangkan pada tahun 2017, kampung ini menjadi destinasi populer bagi wisatawan yang ingin berfoto dan menikmati suasana ceria serta kreativitas masyarakat setempat. Setiap sudut kampung dihiasi dengan lukisan mural yang menggambarkan berbagai tema, menciptakan suasana yang hidup dan penuh warna. Selain keindahan visualnya, Kampung Pelangi juga menawarkan berbagai kegiatan seni dan budaya, serta upaya pemberdayaan masyarakat yang mengajak pengunjung untuk berinteraksi dan belajar tentang kehidupan sehari-hari penduduk lokal. Dengan daya tarik yang unik dan suasana yang ramah, Kampung Pelangi menjadi salah satu tempat yang wajib dikunjungi bagi mereka yang ingin merasakan keindahan dan keunikan Semarang.", R.drawable.kampung),
            Wisata("Pantai Marina", "Pantai Marina adalah destinasi wisata pantai yang terletak di Semarang, Jawa Tengah, yang terkenal dengan pemandangan alamnya yang indah dan suasana yang tenang. Dikenal sebagai tempat yang ideal untuk bersantai, pantai ini menawarkan hamparan pasir putih yang lembut dan ombak yang tenang, cocok untuk berenang dan bermain air. Selain keindahan alamnya, Pantai Marina juga dilengkapi dengan berbagai fasilitas seperti area bermain, gazebo, dan restoran, yang membuatnya menjadi tempat yang sempurna untuk menghabiskan waktu bersama keluarga atau teman. Pengunjung dapat menikmati aktivitas seperti berjemur, berjalan-jalan di tepi pantai, atau menikmati kuliner seafood segar sambil menyaksikan matahari terbenam yang memukau. Dengan akses yang mudah dan suasana yang ramah, Pantai Marina menjadi salah satu pilihan utama bagi wisatawan yang mencari pelarian dari kesibukan kota.", R.drawable.marina),
            Wisata("Brown Canyon Semarang", "Brown Canyon adalah sebuah lokasi wisata alam yang terletak di Semarang, Jawa Tengah, yang terkenal dengan pemandangan tebing-tebing curam berwarna coklat yang menciptakan panorama yang menakjubkan. Awalnya merupakan bekas area pertambangan, tempat ini kini menjadi destinasi populer bagi para pengunjung yang mencari keindahan alam dan spot foto yang unik. Tebing-tebing yang menjulang tinggi dan formasi batuan yang eksotis menawarkan pengalaman yang menawan bagi para pecinta alam dan fotografer. Dengan latar belakang langit biru dan pepohonan hijau, Brown Canyon menciptakan suasana yang memukau dan menarik untuk dijelajahi. Tempat ini menjadi salah satu tujuan wisata alternatif di Semarang, yang menggabungkan keindahan alam dengan petualangan, menjadikannya pilihan menarik untuk menghabiskan waktu bersama keluarga dan teman.", R.drawable.brown_canyon),
            Wisata("Candi Gedong Songo", "Gedong Songo adalah kompleks candi Hindu yang terletak di lereng Gunung Ungaran, Semarang, Jawa Tengah, yang terdiri dari sembilan candi yang dibangun pada abad ke-9. Dikenal dengan keindahan arsitektur dan pemandangan alamnya yang menakjubkan, Gedong Songo menawarkan suasana yang tenang dan spiritual, dikelilingi oleh kebun teh dan hutan pinus. Setiap candi memiliki desain yang unik, mencerminkan pengaruh budaya Hindu, serta kaya akan sejarah dan mitologi. Pengunjung dapat menikmati trekking menyusuri jalan setapak yang menghubungkan candi-candi, serta menikmati panorama alam yang memesona, menjadikan Gedong Songo sebagai salah satu destinasi wisata sejarah dan budaya yang menarik di Indonesia.", R.drawable.gedong_songo),
        )

        val recyclerView: RecyclerView = findViewById(R.id.recyclerViewWisata)
        recyclerView.layoutManager = LinearLayoutManager(this)

        // Mengatur adapter dengan onItemClick untuk membuka DetailActivity
        recyclerView.adapter = WisataAdapter(wisataList) { selectedWisata ->
            val intent = Intent(this, DetailActivity::class.java).apply {
                putExtra("title", selectedWisata.title)
                putExtra("description", selectedWisata.description)
                putExtra("imageResId", selectedWisata.imageResId)
            }
            startActivity(intent)
        }
    }
}


